import type { Academy } from "./academies";
import type { PlaygroundScenario } from "./playground-data";

/**
 * Content source metadata for enterprise contextualization.
 * When an enterprise connects their repo/docs, this tracks what was ingested.
 */
export interface ContentSource {
  id: string;
  type: "github" | "docs" | "tickets" | "incidents" | "api-specs";
  name: string;
  url?: string;
  ingestedAt: string;
  documentCount: number;
  chunkCount: number;
}

/**
 * Enterprise-specific module content that replaces generic examples.
 * Generated by the contextualization engine from ingested sources.
 */
export interface ContextualizedExample {
  id: string;
  moduleId: string;
  title: string;
  description: string;
  category: string;
  bad: {
    label: string;
    code: string;
    explanation: string;
  };
  good: {
    label: string;
    code: string;
    explanation: string;
  };
  sourceRef?: string;
}

/**
 * Team progress tracking for enterprise dashboards.
 */
export interface TeamProgress {
  teamId: string;
  teamName: string;
  members: MemberProgress[];
  completionRate: number;
  avgScore: number;
}

export interface MemberProgress {
  userId: string;
  name: string;
  completedModules: string[];
  playgroundScores: Record<string, number>;
  lastActiveAt: string;
}

/**
 * ContentProvider interface — the abstraction layer for enterprise.
 *
 * Open source: StaticContentProvider reads from TypeScript data files.
 * Enterprise: APIContentProvider fetches from the contextualization API.
 *
 * The UI components don't care which provider they use.
 */
export interface ContentProvider {
  getAcademies(): Promise<Academy[]>;
  getScenarios(academySlug: string): Promise<PlaygroundScenario[]>;
  getExamples(academySlug: string, moduleId: string): Promise<ContextualizedExample[]>;
}

/**
 * Static content provider — reads from bundled TypeScript data files.
 * This is what the open-source version uses.
 */
export const createStaticProvider = (): ContentProvider => ({
  async getAcademies() {
    const { academies } = await import("./academies");
    return academies;
  },

  async getScenarios(academySlug: string) {
    switch (academySlug) {
      case "context-engineering-academy": {
        const { scenarios } = await import("./scenarios/index");
        return scenarios;
      }
      case "llm-evals-academy": {
        const { evalScenarios } = await import("./scenarios/evals/index");
        return evalScenarios;
      }
      case "agentic-rag-academy": {
        const { ragScenarios } = await import("./scenarios/rag/index");
        return ragScenarios;
      }
      case "agent-observability-academy": {
        const { observabilityScenarios } = await import("./scenarios/observability/index");
        return observabilityScenarios;
      }
      case "multi-agent-orchestration-academy": {
        const { multiAgentScenarios } = await import("./scenarios/multi-agent/index");
        return multiAgentScenarios;
      }
      case "tool-use-mcp-academy": {
        const { toolUseScenarios } = await import("./scenarios/tool-use/index");
        return toolUseScenarios;
      }
      default:
        return [];
    }
  },

  async getExamples() {
    return [];
  },
});

/**
 * Enterprise API content provider — fetches contextualized content.
 * Requires NEXT_PUBLIC_ENTERPRISE_API_URL environment variable.
 */
export const createEnterpriseProvider = (apiUrl: string, apiKey: string): ContentProvider => ({
  async getAcademies() {
    const res = await fetch(`${apiUrl}/academies`, {
      headers: { Authorization: `Bearer ${apiKey}` },
    });
    return res.json();
  },

  async getScenarios(academySlug: string) {
    const res = await fetch(`${apiUrl}/scenarios/${academySlug}`, {
      headers: { Authorization: `Bearer ${apiKey}` },
    });
    return res.json();
  },

  async getExamples(academySlug: string, moduleId: string) {
    const res = await fetch(`${apiUrl}/examples/${academySlug}/${moduleId}`, {
      headers: { Authorization: `Bearer ${apiKey}` },
    });
    return res.json();
  },
});

/**
 * Resolve the content provider based on environment.
 * Enterprise: set NEXT_PUBLIC_ENTERPRISE_API_URL and ENTERPRISE_API_KEY
 * Open source: defaults to static provider (no env vars needed)
 */
export const getContentProvider = (): ContentProvider => {
  const apiUrl = process.env.NEXT_PUBLIC_ENTERPRISE_API_URL;
  const apiKey = process.env.ENTERPRISE_API_KEY ?? "";

  if (apiUrl) {
    return createEnterpriseProvider(apiUrl, apiKey);
  }

  return createStaticProvider();
};
